### ISSUE TITLE
`boot watch hoplon` disallows some filesystem changes in output directory 

### ISSUE THREAD

**Issue by pandeiro** [tailrecursion/boot#3]
I have noticed that when running boot watch hoplon, `bower install` fails to install files (while successfully creating a directory structure) inside the :public directory specified in my boot.edn.

**Comment by micha** [comment]
@pandeiro The `:public` directory is managed by boot, actually. Various artifacts are created in temporary staging directories and then synced over to `:public` at the end of the build cycle, sort of similar to `rsync --delete`. This technique means you never have stale files that need to be removed. However, this is also probably why your files are being deleted. (Boot ignores empty directories, which is why you see the directory structure.) 

You have a couple of options:
- Have bower emit files into a staging directory and use the `sync` task to have those copied into `:public` at the end of the build cycle.
- Create a task function that shells out to bower and then use that task when you build with boot.

If you tell me more about what you're doing I can probably be more helpful.

**Comment by pandeiro** [comment]
Thanks micha; actually I'm just glad you could confirm that is the intended behavior. And both of those options are fine. I also am considering outputting bower install to the directory specified in :src-static, which boot then copies over, right? So plenty of options. Thanks again for the response, and for the interesting project.

**Comment by micha** [comment]
@pandeiro Emitting the files into a `:src-static` directory should work fine, I think. Those directories are synced  each time the `watch` task polls for changes, regrdless of whether the source files needed to be rebuilt, so you don't need to trigger rebuilding the project for the modifications in `:src-static` dirs to be copied over. When bower rebuilds your artifacts it'll copy them over right away, which is probably what you want. Good luck and have fun!
