### ISSUE TITLE
boot fails with itsy

### ISSUE THREAD

**Issue by renegr** [tailrecursion/boot#30]
When I add **[itsy "0.1.1"]** to the dependencies in the build.boot, it fails to start with `boot development`.

Can you reproduce this event?

**Comment by mynomoto** [comment]
I have no idea why this is happening, but I can confirm that boot just hang on a new project with this dep.

**Comment by jumblerg** [comment]
in the absence of more information, it is likely that one or more of itsy's transitive dependencies (probably the apache http-client libraries wrapped by clj-http) uses a different version of a library already on the classpath that is required by boot itself.  this happens because, unlike leiningen, boot uses a single jvm.  the next soon-to-be-released version of boot uses classloader isolation to prevent this problem from occurring.

**Comment by renegr** [comment]
Thanks for the very quick response! Looking very much forward to the next Release. Any more details on the release date?

**Comment by jumblerg** [comment]
if micha's recent progress on the v2-docs branch is any indication, i suspect it will be quite soon.

**Comment by create-renegr** [comment]
For future references: boot v2 moved here: https://github.com/boot-clj/boot
